version: '3.9'
services:
  db:
    image: mysql:8.0.32
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: Portugal/Lisbon
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: spring_boot_course
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - demo-network
  spring-boot-course:
    image: david9morais/java-spring-boot-api
    restart: always
    build:  ./java-spring-boot-api
    working_dir: /java-spring-boot-api
    environment:
      TZ: Europe/Lisbon
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/spring_boot_course?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123
    ports:
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - demo-network
networks:
  demo-network:
    driver: bridge